### ISSUE TITLE
Hangout para tirar dúvidas

### ISSUE THREAD

**Issue by msfernandes** [silegis-mg/editor-articulacao#5]
Olá! Sou desenvolvedor do Laboratório Hacker da Câmara dos Deputados e estamos construindo uma ferramenta para os consultores da Casa e gostamos bastante do editor-articulacao e estamos querendo incluí-lo no projeto. Mas temos algumas dúvidas e gostaríamos de saber se poderia rolar um hangout pra trocarmos uma ideia... 
Desde já, agradeço!

**Comment by juliomelo** [comment]
Claro! Poderíamos marcar para quinta-feira, 02/maio, 10h?

**Comment by msfernandes** [comment]
Massa! Meu email: matheus.souza.fernandes@gmail.com
Só dar um toque!

**Comment by juliomelo** [comment]
https://hangouts.google.com/call/-HpnfH6in9IxdADJYj76AEEE
