### ISSUE TITLE
Apenas alguns erros são renderizados instantaneamente ao colar um novo texto. 

### ISSUE THREAD

**Issue by cfviotti** [silegis-mg/editor-articulacao#7]
![silegisbug](https://user-images.githubusercontent.com/6797129/58983853-16515900-87ae-11e9-9339-48f440148997.gif)

Quando colamos um texto que tenha erros em diversas articulações, apenas alguns erros são renderizados instantaneamente. É necessário navegar pelo texto alterando o contexto para que eventualmente os erros reminescentes sejam renderizados.

Há algum caminho sugerido para investigar uma solução desse bug?

**Comment by juliomelo** [comment]
A validação ocorre conforme mudança da seleção/cursor no editor, para garantir um bom desempenho, evitando a validação de dispositivos não alterados.

https://github.com/silegis-mg/editor-articulacao/blob/f0c35dd7a05627ac647892654009cb50b1cb567a/src/EditorArticulacaoController.js#L293-L300

O dispositivo onde está o cursor é desconsiderado atualmente da validação: (seria melhor tornar isto configurável?)

https://github.com/silegis-mg/editor-articulacao/blob/f0c35dd7a05627ac647892654009cb50b1cb567a/src/EditorArticulacaoController.js#L222-L229

E a normalização valida apenas o dispositivo anterior e posterior ao cursor:

https://github.com/silegis-mg/editor-articulacao/blob/f0c35dd7a05627ac647892654009cb50b1cb567a/src/EditorArticulacaoController.js#L255-L258

Entretanto, durante a colagem, a validação não é invocada para os novos elementos, mas apenas a atualização de contexto, provocando o defeito observado:

https://github.com/silegis-mg/editor-articulacao/blob/f0c35dd7a05627ac647892654009cb50b1cb567a/src/ClipboardController.js#L174

A validação deveria ser chamada para cada novo elemento incluído no editor. Para evitar validação redundante, a validação do contexto deveria, neste caso, ser omitida ou a validação dos novos elementos poderia desconsiderar o dispositivo anterior ao cursor na posição após a colagem.

**Comment by juliomelo** [comment]
Estou na dúvida se o melhor seria chamar explicitamente a validação na colagem ou substituir todas as chamadas de validação por um MutationObserver no controller de validação e, assim, garantir a validação em qualquer alteração, até aquele realizadas externamente por JavaScript estranhos à biblioteca.

**Comment by juliomelo** [comment]
Foi feita a correção realizando chamada explícita. A biblioteca atualmente não depende do MutationObserver e a sua introdução pode diminuir o suporte a navegadores mais antigos. Segundo o caniuse.com, a maior parte dos navegadores já teriam suporte.

De qualquer maneira, se for o caso de refatorar o código para usar MutationObserver, que permitiria a validação até mesmo caso o editor seja alterado externamente, extrapola o escopo deste bug.

**Comment by cfviotti** [comment]
Perfeito Julio. Estávamos discutindo aqui que esse comportamento de validação na normalização do contexto é suficiente, mas de fato poderia ser diferente para o caso de colagem de texto. Assim está ótimo!
